repos:
  # Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
  # Black
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  # Flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-typing-imports==1.9.0
        ]
        args:
        - --max-line-length=120
        - --max-complexity=20
        - --ignore=E203,E266,E501,W503,F403,F401,E501,E722,C901
        - --select=B,C,E,F,W,T4,B9
  # Isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--profile",
          "black"
        ]
