services:
  # Servicio FastAPI
  fastapi-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=Template API
      - DEBUG=false
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=template_db
      - POSTGRES_USER=template_user
      - POSTGRES_PASSWORD=template_password
      - POSTGRES_PORT=5432
      - API_HOST=0.0.0.0
      - API_PORT=8080
    depends_on:
      - postgres
    networks:
      - template-network
    restart: unless-stopped

  # Servicio PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: template_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/SQL:/docker-entrypoint-initdb.d
    networks:
      - template-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template_user -d template_db"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volúmenes persistentes
volumes:
  postgres_data:

# Red personalizada
networks:
  template-network:
    driver: bridge